/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zh_opencvproto_Detector */

#ifndef _Included_com_zh_opencvproto_Detector
#define _Included_com_zh_opencvproto_Detector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zh_opencvproto_Detector
 * Method:    detect
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_zh_opencvproto_Detector_detect
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
