/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zh_opencvncnn_Detector */

#ifndef _Included_com_zh_opencvncnn_Detector
#define _Included_com_zh_opencvncnn_Detector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zh_opencvncnn_Detector
 * Method:    detect
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_zh_opencvncnn_Detector_detect
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
